name: Schedule test manual trigger

on:
  workflow_dispatch:
    inputs:
        test-folder:
          type: string
          description: 'Test folder to run'
          required: true

jobs:

  trigget-tests:
    name: Trigger tests for test folder - ${{ inputs.test-folder }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Load testing variables for ${{ inputs.test-folder }}
        id: load_variables
        run: |
          variables_file="${{ github.workspace }}/${{ inputs.test-folder }}/variables.json"
          echo "$(jq '. += {"test-folder":"${{ inputs.test-folder }}"}' $variables_file)" > $variables_file
          echo "Loading JSON variables:"
          json=$(cat $variables_file)
          echo "$json"
          json=$(jq -c . $variables_file)
          # change it to one line
          echo "$json"
          
          echo "configuration=$json" >> $GITHUB_ENV
          
          # echo "configuration<<EOF" >> $GITHUB_ENV
          # echo "$json" >> $GITHUB_ENV
          # echo "EOF" >> $GITHUB_ENV

      - name: Trigger test workflow for ${{ inputs.test-folder }}
        uses: actions/github-script@v7
        env:
          configuration: ${{ env.configuration }}
        with:
          github-token: ${{ secrets.ATF_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'CZERTAINLY',
              repo: 'CZERTAINLY-Automated-Testing-Framework',
              workflow_id: 'run-test-folder-action.yml',
              ref: 'main',
              inputs: {
                'configuration': '${{ env.configuration }}',
              }
            })
